version: '3.8'

services:
  import-las:
    image: supervisely/import-las-format-pdal:1.0.0
    container_name: import-las-format
    network_mode: host
    volumes:
      - ./src:/app
      - ./local.env:/app/local.env:ro
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    env_file:
      - local.env
    working_dir: /app
    command: python /app/main.py
